select* from component_definition_values
where upper(display_value) like '%ULTIMATE%'

SELECT * FROM PACKAGE_COMPONENT_MEMBERS
WHERE COMPONENT_ID =29399

CREATE TABLE ULTIMATE AS
SELECT * FROM PRODUCT
WHERE COMPONENT_ID =29399
AND (BILLING_INACTIVE_DT IS NULL OR BILLING_INACTIVE_DT >=TO_DATE('28102014','DDMMYYYY'))

CREATE TABLE ULTIMATE1 AS
SELECT DISTINCT PARENT_ACCOUNT_NO, PARENT_SUBSCR_NO
FROM ULTIMATE

CREATE TABLE ULTIMATE_BI AS
SELECT DISTINCT BI.BILL_REF_NO FROM ULTIMATE1 U, BILL_INVOICE BI
WHERE U.PARENT_ACCOUNT_NO=BI.ACCOUNT_NO
AND BI.PREP_DATE >=TO_DATE('28102014','DDMMYYYY')
AND BI.PREP_STATUS=1
AND BI.PREP_ERROR_CODE IS NULL

-------------------------- NÃO CONSIGO RODAR ----------------------
CREATE TABLE ULTIMATE_BID AS
SELECT BID.* FROM ULTIMATE_BI U, BILL_INVOICE_DETAIL BID 
WHERE U.BILL_REF_NO = BID.BILL_REF_NO
AND BID.TYPE_CODE=2
AND BID.COMPONENT_ID=29399

--------------------------------------------------------------------

CREATE TABLE ULTIMATE_BID AS
SELECT BI.* 
FROM ULTIMATE U, BILL_INVOICE B, BILL_INVOICE_dETAIL BI
WHERE U.PARENT_ACCOUNT_NO=B.ACCOUNT_NO
AND B.BILL_REF_NO=BI.BILL_REF_NO
AND BI.SUBSCR_NO=U.PARENT_SUBSCR_NO
AND U.BILLING_ACCOUNT_NO=1264862
AND U.TRACKING_ID=BI.TRACKING_ID
AND U.TRACKING_ID_SERV=BI.TRACKING_ID_SERV
--AND B.PREP_DATE >=TO_DATE('28102014','DDMMYYYY')
AND BI.TYPE_CODE=2
AND B.PREP_STATUS=1
AND B.PREP_ERROR_CODE IS NULL
