ALTER TABLE ARBORGVT_BILLING.GVT_AVULSO_FATURACD
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARBORGVT_BILLING.GVT_AVULSO_FATURACD CASCADE CONSTRAINTS;

CREATE TABLE ARBORGVT_BILLING.GVT_AVULSO_FATURACD
(
  ACCOUNT_NO   NUMBER(10)                       NOT NULL,
  BILL_REF_NO  NUMBER(10)
)
TABLESPACE GVT_FAT_CONTAB_DAT
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ARBORGVT_BILLING.GVT_AVULSO_FATURACD_PK ON ARBORGVT_BILLING.GVT_AVULSO_FATURACD
(ACCOUNT_NO)
LOGGING
TABLESPACE GVT_FAT_CONTAB_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM GVT_AVULSO_FATURACD;

CREATE PUBLIC SYNONYM GVT_AVULSO_FATURACD FOR ARBORGVT_BILLING.GVT_AVULSO_FATURACD;


ALTER TABLE ARBORGVT_BILLING.GVT_AVULSO_FATURACD ADD (
  CONSTRAINT GVT_AVULSO_FATURACD_PK
 PRIMARY KEY
 (ACCOUNT_NO)
    USING INDEX 
    TABLESPACE GVT_FAT_CONTAB_DAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

GRANT SELECT ON ARBORGVT_BILLING.GVT_AVULSO_FATURACD TO R_ITBILLING_RO;
