ALTER TABLE ARBOR.GVT_DET_FATURAMENTO_CD
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARBORGVT_BILLING.GVT_DET_FATURAMENTO_CD CASCADE CONSTRAINTS;

CREATE TABLE ARBOR.GVT_DET_FATURAMENTO_CD
(
  EXTERNAL_ID  VARCHAR2(144 BYTE)               NOT NULL
);


select * from GVT_CONTESTADOS_COBILLING

select * from gvt_historico_cdrs_ajustados where dt_ajuste > sysdate - 1 