drop table G0023421SQL.GVT_RAJADAS_BILL;

CREATE TABLE G0023421SQL.GVT_RAJADAS_BILL
(
  EXTERNAL_ID  VARCHAR2(12 BYTE),
  ACCOUNT_NO   NUMBER(10),
  BILL_REF_NO  NUMBER(10),
  BAIXA        NUMBER(10),
  V_DEBITO     NUMBER(10),
  V_PAGO       NUMBER(10),
  DT_PAGTO     DATE,
  MSG          VARCHAR2(2000 BYTE),
  NSA          VARCHAR2(12 BYTE),
  STATUS       NUMBER(10)
 );
 
 grant all on G0023421SQL.GVT_RAJADAS_BILL to public;
 
 
 select * from GVT_RAJADAS_BILL