SELECT 1 
  FROM CUSTOMER_ID_EQUIP_MAP, SERVICE
 WHERE PARENT_ACCOUNT_NO in (SELECT ACCOUNT_NO FROM GVT_FEBRABAN_ACCOUNTS GFA WHERE GFA.INACTIVE_DATE IS NULL)
   AND EXTERNAL_ID_TYPE = 6
   AND SERVICE.SUBSCR_NO = CUSTOMER_ID_EQUIP_MAP.SUBSCR_NO
   AND SERVICE.SUBSCR_NO_RESETS = CUSTOMER_ID_EQUIP_MAP.SUBSCR_NO_RESETS