SELECT POINT_CLASS 
FROM USAGE_POINTS
WHERE POINT = ?
AND   INACTIVE_DT IS NULL
UNION
SELECT MIN(point_class)
FROM USAGE_POINTS
WHERE POINT_STATE_ABBR = RPAD(?, 6)
AND   INACTIVE_DT IS NULL
AND LENGTH(point_class)=5

ONDE POINT = COLUNA 2 DO PASSO 6
     POINT_STATE_ABBR = COLUNA 7 DO PASSO 4

SELECT * 
FROM USAGE_POINTS

select * from GVT_FEBRABAN_PONTA_B_ARBOR where EMF_EXT_ID in ('SPO-3012IVVPH-032')