select count(1) from GVT_FEBRABAN_PONTA_B_ARBOR_BK

select count(1) from GVT_FEBRABAN_PONTA_B_ARBOR

select * from GVT_FEBRABAN_PONTA_B_ARBOR_bk where EMF_EXT_ID not in (select EMF_EXT_ID from GVT_FEBRABAN_PONTA_B_ARBOR)

select * from GVT_FEBRABAN_PONTA_B_ARBOR_bk where EMF_EXT_ID not in (select EMF_EXT_ID from GVT_FEBRABAN_PONTA_B_ARBOR)


select INACTIVE_DATE
from CUSTOMER_ID_EQUIP_MAP, service
WHERE SERVICE.PARENT_ACCOUNT_NO = 831931
AND SERVICE.SUBSCR_NO = CUSTOMER_ID_EQUIP_MAP.SUBSCR_NO
AND SERVICE.SUBSCR_NO_RESETS = CUSTOMER_ID_EQUIP_MAP.SUBSCR_NO_RESETS
AND   EXTERNAL_ID = '999997308336'
AND   EXTERNAL_ID_TYPE = 7
AND   INACTIVE_DATE IS NOT NULL