
Insert into ARBORGVT_PAYMENTS.GVT_FEBRABAN_PONTA_B_ARBOR
  (ROW_ID,     CMF_EXT_ID, EMF_EXT_ID        , SERVICE_START                                          , DEGRAU, VELOCIDADE, UNID_VELOCIDADE,    CNLA,    CNLB,                ADDRESS_B, COMPL_B, DISTRICT_B)
Values
  ('3-W2R1MY', '999985081748', 'BSA-30W2TACH-9698', TO_DATE('05/13/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 's/'  , 9, 'MB'   , '61000', '61000', 'BL         CRS 506 BLOCO A 506',  '', 'DF');


SELECT Q.ROW_ID,
       A.EXTERNAL_ID as CMF_EXT_ID,
       EIEM.EXTERNAL_ID as EMF_EXT_ID,
       --SERVICE.EMF_CONFIG_ID,
       --ECI.DISPLAY_VALUE,
       SERVICE.SERVICE_ACTIVE_DT as SERVICE_START,
       's/' as DEGRAU,
       GPV.VELOCITY as VELOCIDADE,
       GPV.VELOCITY as UNID_VELOCIDADE,
       '' as CNLA,
       '' as CNLB,
       LOCAL_ADDRESS.ADDRESS_1 as ADDRESS_B,
       LOCAL_ADDRESS.ADDRESS_2 as COMPL_B, 
       LOCAL_ADDRESS.STATE as DISTRICT_B 
FROM CUSTOMER_ID_EQUIP_MAP EIEM,
     SERVICE,
     CUSTOMER_ID_ACCT_MAP A,
     EMF_CONFIG_ID_VALUES ECI,
     PRODUCT EP,
     LOCAL_ADDRESS,
     SERVICE_ADDRESS_ASSOC,       
     GVT_PRODUCT_VELOCITY GPV,
     S_QUOTE_SOLN Q
WHERE service.parent_ACCOUNT_NO in (select account_no from GVT_FEBRABAN_ACCOUNTS)
AND   SERVICE_ADDRESS_ASSOC.address_id = LOCAL_ADDRESS.address_id
AND   SERVICE_ADDRESS_ASSOC.account_no = service.parent_account_no
AND   SERVICE_ADDRESS_ASSOC.subscr_no = service.subscr_no
AND   SERVICE_ADDRESS_ASSOC.subscr_no_resets = service.subscr_no_resets
AND   EIEM.EXTERNAL_ID_TYPE = 7
AND   A.ACCOUNT_NO = SERVICE.PARENT_ACCOUNT_NO
AND   EIEM.INACTIVE_DATE IS NULL
AND   EIEM.SUBSCR_NO = SERVICE.SUBSCR_NO
AND   EIEM.SUBSCR_NO = EP.parent_SUBSCR_NO (+)
AND   EP.TRACKING_ID = GPV.TRACKING_ID (+)
AND   EP.TRACKING_ID_SERV = GPV.TRACKING_ID_SERV (+)
AND   SERVICE.EMF_CONFIG_ID = ECI.EMF_CONFIG_ID
AND   ECI.LANGUAGE_CODE = 2
AND   EIEM.EXTERNAL_ID = Q.ASSET_NUM


select Q.ROW_ID, A.EXTERNAL_ID as CMF_EXT_ID, C.EXTERNAL_ID as EMF_EXT_ID, A.ACCOUNT_NO, 
       p.SERVICE_START, P.ADRESS_B, P.COMPL_B, P.DISTRICT_B, P.VELOCIDADE, P.UNID_VELOCIDADE, P.CNL, A.ACCOUNT_NO
  from customer_id_acct_map a,
       service s,
       customer_id_equip_map c,
       s_org_ext x,
       s_quote_soln q,
      BQ_FEBRABAN_PONTA p           
 where A.ACCOUNT_NO = S.PARENT_ACCOUNT_NO
   and S.SUBSCR_NO = C.SUBSCR_NO
   and S.SUBSCR_NO_RESETS = C.SUBSCR_NO_RESETS
   and A.EXTERNAL_ID = '999983129627'
   and X.X_ACCT_ID_NUM = A.EXTERNAL_ID
   and X.x_acct_id_num = '999983129627'
   and P.EXTERNAL_ID = A.EXTERNAL_ID
   and C.EXTERNAL_ID = q.ASSET_NUM