INSERT INTO ${TABELA} (ACCOUNT_NO, BILL_PERIOD,PROCESSO, DURACAO)

SELECT DISTINCT ACCOUNT_NO,BILL_PERIOD,1,1
           FROM GVT_TEMP_CONTAS_PROFORMA
WHERE UPPER(BILL_PERIOD) IN (SELECT BILL_PERIOD FROM GVT_PROCESSAMENTO_CICLO WHERE UPPER(PROCESSAMENTO) = UPPER('${CICLO}'))

UNION

SELECT DISTINCT GPC.ACCOUNT_NO, CMF.BILL_PERIOD, 1, 1
  FROM ARBORGVT_BILLING.GVT_PROFORMA_CONTAS_SME GPC,
       CMF
WHERE GPC.ACCOUNT_NO = CMF.ACCOUNT_NO
--AND UPPER(BILL_PERIOD) IN (SELECT BILL_PERIOD FROM GVT_PROCESSAMENTO_CICLO WHERE UPPER(PROCESSAMENTO) = UPPER('${CICLO}'))
  AND CMF.ACCOUNT_CATEGORY BETWEEN 10 AND 11;