SELECT count(1)
  FROM PRODUCT CP,
       PRODUCT_CHARGE_MAP PCM,
       cmf
 WHERE CP.BILLING_ACCOUNT_NO = CMF.ACCOUNT_NO
   AND CP.ELEMENT_ID IN (11402,11110)
   AND CP.PARENT_SUBSCR_NO IS NULL
   AND (CP.PRODUCT_INACTIVE_DT is null or (CP.PRODUCT_INACTIVE_DT is not null and PCM.BILLED_THRU_DT < CP.PRODUCT_INACTIVE_DT))
   AND CP.TRACKING_ID = PCM.TRACKING_ID 
   AND CP.TRACKING_ID_SERV = PCM.TRACKING_ID_SERV
   AND CMF.ACCOUNT_CATEGORY in (10,11)
   AND CMF.DATE_INACTIVE is null
   AND not exists (select 1 from CONTRACT_ASSIGNMENTS_HQ hq where hq.account_no = CMF.account_no)
 