SELECT *
 FROM CMF
 WHERE NO_BILL=0
 AND ACCOUNT_STATUS!=-2
 AND ACCOUNT_CATEGORY IN (9,10,11)
 AND CONTACT1_PHONE IS NOT NULL
 AND CUST_ZIP IS NOT NULL
 --AND UPPER(BILL_PERIOD) IN (SELECT BILL_PERIOD FROM GVT_PROCESSAMENTO_CICLO WHERE UPPER(PROCESSAMENTO) = UPPER('${MAX}'))
 AND NEXT_BILL_DATE >= SYSDATE
 AND EXISTS (
             SELECT 1 
               FROM SERVICE, SERVICE_VIEW SV
              WHERE SERVICE.PARENT_ACCOUNT_NO = CMF.ACCOUNT_NO
                AND SERVICE.PARENT_ACCOUNT_NO = SV.PARENT_ACCOUNT_NO
                AND VIEW_STATUS > 0 
                AND SERVICE.SERVICE_INACTIVE_DT >= (SYSDATE - 90)
           )
and account_no = 10229294;