DROP TABLE G0023421SQL.ATIVOS CASCADE CONSTRAINTS;

CREATE TABLE G0023421SQL.ATIVOS
(
  EXTERNAL_ID  VARCHAR2(144 BYTE)               NULL,
  ACCOUNT_NO   NUMBER(10)                       NULL,
  BILL_REF_NO  NUMBER(10)                       NULL,
  TOTAL_PAGO   NUMBER
);