Insert into G0023421SQL.GVT_VAL_PLANO
   (PLANO, COMPONENT_ID, COMPONENTE, ELEMENTOSCOMPONENTE, ELEMENTO, TIPOELEMENTO, ARQUIVO, NOME_PLANO)
 Values
   ('GVT - Na Medida Casa', '25011', 'Plano Basico - 5 minutos - Conta', '4', NULL, 
    'RC - Conta', NULL, 'LAVOISIER');
    
select * from G0023421SQL.GVT_VAL_PLANO

delete from G0023421SQL.GVT_VAL_PLANO where COMPONENT_ID = 25011