DROP TABLE ARBORGVT_CORPORATE. GVT_FEBRABAN_PONTA_B_ARBOR CASCADE CONSTRAINTS;

CREATE TABLE ARBORGVT_CORPORATE. GVT_FEBRABAN_PONTA_B_ARBOR
(
  ROW_ID           CHAR(15 BYTE),
  CMF_EXT_ID       VARCHAR2(48 BYTE),
  EMF_EXT_ID       VARCHAR2(48 BYTE),
  SERVICE_START    DATE,
  SERVICE_END      DATE,
  DEGRAU           CHAR(2 BYTE),
  VELOCIDADE       NUMBER(6),
  UNID_VELOCIDADE  CHAR(10 BYTE),
  CNLA             CHAR(5 BYTE),
  CNLB             CHAR(5 BYTE),
  ADDRESS_B        VARCHAR2(75 BYTE),
  NUMBER_B         VARCHAR2(10 BYTE),
  COMPL_B          VARCHAR2(75 BYTE),
  DISTRICT_B       VARCHAR2(75 BYTE),
  PHONE_NUMBER     VARCHAR2(30 BYTE)
)
TABLESPACE GVT_DEFAULT_DAT
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ARBORGVT_CORPORATE.GVT_FEBRABAN_ARBOR_KEY0001 ON ARBORGVT_CORPORATE.GVT_FEBRABAN_PONTA_B_ARBOR
(EMF_EXT_ID, ROW_ID)
LOGGING
TABLESPACE GVT_DEFAULT_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM ARBOR.GVT_FEBRABAN_PONTA_B_ARBOR;

CREATE SYNONYM ARBOR.GVT_FEBRABAN_PONTA_B_ARBOR FOR ARBORGVT_CORPORATE.GVT_FEBRABAN_PONTA_B_ARBOR;


DROP PUBLIC SYNONYM GVT_FEBRABAN_PONTA_B_ARBOR;

CREATE PUBLIC SYNONYM GVT_FEBRABAN_PONTA_B_ARBOR FOR ARBORGVT_PAYMENTS.GVT_FEBRABAN_PONTA_B_ARBOR;


ALTER TABLE ARBORGVT_CORPORATE.GVT_FEBRABAN_PONTA_B_ARBOR ADD (
  CHECK ("ROW_ID" IS NOT NULL),
  CHECK ("CMF_EXT_ID" IS NOT NULL),
  CHECK ("EMF_EXT_ID" IS NOT NULL),
  CHECK ("SERVICE_START" IS NOT NULL),
  CHECK ("DEGRAU" IS NOT NULL),
  CHECK ("VELOCIDADE" IS NOT NULL),
  CHECK ("UNID_VELOCIDADE" IS NOT NULL),
  CHECK ("CNLA" IS NOT NULL));

GRANT SELECT ON ARBORGVT_CORPORATE.GVT_FEBRABAN_PONTA_B_ARBOR TO R_DATAQUALITY;

GRANT SELECT ON ARBORGVT_CORPORATE.GVT_FEBRABAN_PONTA_B_ARBOR TO AR;
