SELECT PREP_DATE,  ORIGEM, CICLO, SEGMENTO, TIPO, count(*) MEDIDA
FROM
(
SELECT
    BI.PREP_DATE PREP_DATE,
    'PROD' ORIGEM,
    C.BILL_PERIOD CICLO,
    SEG.SEGMENTO,
    'VOL' TIPO    
FROM
    GVT_FEBRABAN_BILL_INVOICE FEB,
    BILL_INVOICE BI,
    CMF C,
    PVA_T_PARAM_SEGMENTOS SEG
WHERE
    BI.PREP_DATE >= to_date($PREP_DATE_CONTROL_M,'YYYYMMDDHH24:MI:SS')
    AND FEB.BILL_REF_NO = BI.BILL_REF_NO
    AND FEB.BILL_REF_RESETS = BI.BILL_REF_RESETS
    AND C.ACCOUNT_NO = BI.ACCOUNT_NO
    AND SEG.ACCOUNT_CATEGORY = C.ACCOUNT_CATEGORY

UNION ALL

SELECT
    BI.PREP_DATE PREP_DATE,
    'PROD' ORIGEM,
    C.BILL_PERIOD CICLO,
    SEG.SEGMENTO,
    'VOL' TIPO    
FROM
    GVT_FBB_BILL_INVOICE FEB,
    BILL_INVOICE BI,
    CMF C,
    PVA_T_PARAM_SEGMENTOS SEG
WHERE
    BI.PREP_DATE >= to_date($PREP_DATE_CONTROL_M,'YYYYMMDDHH24:MI:SS')
    AND FEB.BILL_REF_NO = BI.BILL_REF_NO
    AND FEB.BILL_REF_RESETS = BI.BILL_REF_RESETS
    AND C.ACCOUNT_NO = BI.ACCOUNT_NO
    AND SEG.ACCOUNT_CATEGORY = C.ACCOUNT_CATEGORY

)
GROUP BY
    PREP_DATE,
    ORIGEM,
    CICLO,
    SEGMENTO,
    TIPO
-----------------------------------------------------------------------
UNION ALL

SELECT PREP_DATE,  ORIGEM, CICLO, SEGMENTO, TIPO, sum(valor) MEDIDA
FROM
(
SELECT
    BI.PREP_DATE PREP_DATE,
    'PROD' ORIGEM,
    C.BILL_PERIOD CICLO,
    SEG.SEGMENTO,
    'FIN' TIPO,
    FEED.VALOR VALOR
FROM
    GVT_FEBRABAN_BILL_INVOICE FEB,
    BILL_INVOICE BI,
    CMF C,
    PVA_T_PARAM_SEGMENTOS SEG,
    PVA_T_FEED_FILE FEED
WHERE
    BI.PREP_DATE >= to_date($PREP_DATE_CONTROL_M,'YYYYMMDDHH24:MI:SS')
    AND FEB.BILL_REF_NO = BI.BILL_REF_NO
    AND FEB.BILL_REF_RESETS = BI.BILL_REF_RESETS
    AND C.ACCOUNT_NO = BI.ACCOUNT_NO
    AND SEG.ACCOUNT_CATEGORY = C.ACCOUNT_CATEGORY
    AND FEED.NUMERO_FATURA = BI.BILL_REF_NO

UNION ALL

SELECT
    BI.PREP_DATE PREP_DATE,
    'PROD' ORIGEM,
    C.BILL_PERIOD CICLO,
    SEG.SEGMENTO,
    'FIN' TIPO,
    FEED.VALOR VALOR    
FROM
    GVT_FBB_BILL_INVOICE FEB,
    BILL_INVOICE BI,
    CMF C,
    PVA_T_PARAM_SEGMENTOS SEG,
    PVA_T_FEED_FILE FEED
WHERE
    BI.PREP_DATE >= to_date($PREP_DATE_CONTROL_M,'YYYYMMDDHH24:MI:SS')
    AND FEB.BILL_REF_NO = BI.BILL_REF_NO
    AND FEB.BILL_REF_RESETS = BI.BILL_REF_RESETS
    AND C.ACCOUNT_NO = BI.ACCOUNT_NO
    AND SEG.ACCOUNT_CATEGORY = C.ACCOUNT_CATEGORY
    AND FEED.NUMERO_FATURA = BI.BILL_REF_NO

)
GROUP BY
    PREP_DATE,
    ORIGEM,
    CICLO,
    SEGMENTO,
    TIPO
