SELECT --Q.ROW_ID,
       --A.EXTERNAL_ID as CMF_EXT_ID,
       EIEM.EXTERNAL_ID as EMF_EXT_ID,
       --SERVICE.EMF_CONFIG_ID,
       --ECI.DISPLAY_VALUE,
       --Q.ASSET_NUM,
       SERVICE.SERVICE_ACTIVE_DT as SERVICE_START,
       null as SERVICE_END,
       's/' as DEGRAU,
       RTRIM(upper(GPV.VELOCITY), 'KMBGT') as VELOCIDADE,
       LTRIM(GPV.VELOCITY, '1234567890.') as UNID_VELOCIDADE,
       CNL.point_class as CNLA,
       CNL.point_class as CNLB,
       LOCAL_ADDRESS.ADDRESS_1 as ADDRESS_B,
       LOCAL_ADDRESS.ADDRESS_2 as COMPL_B, 
       LOCAL_ADDRESS.STATE as DISTRICT_B,
       null as PHONE_NUMBER
       -- ,display_value
FROM   CUSTOMER_ID_EQUIP_MAP EIEM,
       SERVICE,
       EMF_CONFIG_ID_VALUES ECI,
       PRODUCT EP,
       LOCAL_ADDRESS,
       SERVICE_ADDRESS_ASSOC,          
       GVT_PRODUCT_VELOCITY GPV,
       (SELECT MIN(point_class) as point_class,
               trim(POINT_STATE_ABBR) as POINT
          FROM USAGE_POINTS
         WHERE INACTIVE_DT IS NULL
           AND LENGTH(point_class)=5
        GROUP BY POINT_STATE_ABBR) CNL 
WHERE  service.parent_ACCOUNT_NO in (SELECT ACCOUNT_NO FROM GVT_FEBRABAN_ACCOUNTS GFA WHERE GFA.INACTIVE_DATE IS NULL)
  AND  SERVICE_ADDRESS_ASSOC.address_id = LOCAL_ADDRESS.address_id
  AND  SERVICE_ADDRESS_ASSOC.account_no = service.parent_account_no
  AND  SERVICE_ADDRESS_ASSOC.subscr_no = service.subscr_no
  AND  SERVICE_ADDRESS_ASSOC.subscr_no_resets = service.subscr_no_resets
  AND  EIEM.EXTERNAL_ID_TYPE = 7
  AND  EIEM.INACTIVE_DATE IS NULL
  AND  EIEM.SUBSCR_NO = SERVICE.SUBSCR_NO
  AND  EIEM.SUBSCR_NO = EP.parent_SUBSCR_NO (+)
  AND  EP.TRACKING_ID = GPV.TRACKING_ID (+)
  AND  EP.TRACKING_ID_SERV = GPV.TRACKING_ID_SERV (+)
  AND  SERVICE.EMF_CONFIG_ID = ECI.EMF_CONFIG_ID
  AND  ECI.LANGUAGE_CODE = 2
  AND   CNL.POINT = LOCAL_ADDRESS.STATE
  AND  NOT EXISTS (SELECT 1 FROM GVT_FEBRABAN_PONTA_B_ARBOR B WHERE B.EMF_EXT_ID = EIEM.EXTERNAL_ID)
