SELECT * FROM EXTERNAL_ID_ACCT_MAP C, EXTERNAL_ID_EQUIP_MAP E
WHERE C.EXTERNAL_ID = '3-1KPX9RR'
AND C.ACCOUNT_NO = E.ACCOUNT_NO
AND E.EXTERNAL_ID = 'AJU-301KPYJ9D-16032-301KPYJ9F'
AND E.EXTERNAL_ID_TYPE = 1
--AND E.ACTIVE_DATE >= TO_DATE(SUBSTR(P_START_DATE, 1, 8), 'YYYY/MM/DD')
AND TO_CHAR(E.ACTIVE_DATE , 'yyyymmddhh24miss') <= 20151010000000
AND E.INACTIVE_DATE IS NULL