SELECT /*+ ORDERED */
       PAYMENT_DUE_DATE,
       COUNT(*)
FROM   BILL_INVOICE A, gvt_avulso_retail_prod B
WHERE  A.ACCOUNT_NO = B.ACCOUNT_NO
AND    A.PREP_DATE >= TO_DATE ('2015092903:37:49','YYYYMMDDHH24:MI:SS')
AND    A.PREP_STATUS=1
AND    A.PREP_ERROR_CODE IS NULL
GROUP BY PAYMENT_DUE_DATE;


 SELECT * FROM arborgvt_billing.gvt_credito_interrupcao_LOG;