drop table GVT_VAL_LOG_EIF;

CREATE TABLE GVT_VAL_LOG_EIF
(
  EIF      VARCHAR2(10 BYTE),
  INICIO   VARCHAR2(30 BYTE),
  FIM      VARCHAR2(30 BYTE),
  TIPO     VARCHAR2(30 BYTE),
  BILL_REF_NO NUMBER(12)
); 


