SELECT /*+ PARALLEL (A 12) FULL(A) */ COUNT(*) FROM BILL_INVOICE A
WHERE PREP_DATE <= sysdate
AND FORMAT_STATUS IN (0,3)
AND PREP_STATUS IN (1,4)
AND BACKOUT_STATUS = 0
AND ACCOUNT_NO IN (SELECT ACCOUNT_NO FROM CMF WHERE ACCOUNT_CATEGORY IN (12,13,14,15,21,22)
                   UNION ALL
                   SELECT ACCOUNT_NO FROM bipp02_corp
                   UNION ALL
                   SELECT ACCOUNT_NO FROM CONTRACT_ASSIGNMENTS_HQ WHERE TRACKING_ID IN (SELECT TRACKING_ID FROM ARBORGVT_BILLING.CONTA_CORPORATE_HQ)) 
                   
                   CUST_ID_EQUIP_MAP_VIEW_ATRIG
                   
SELECT PAYMENT_DUE_DATE, COUNT(*)
FROM BILL_INVOICE A, 
     bipp27_corp B
WHERE A.ACCOUNT_NO = B.ACCOUNT_NO
AND A.PREP_DATE >= TO_DATE ('2015072717:40:18','YYYYMMDDHH24:MI:SS')
AND A.PREP_ERROR_CODE IS NULL
AND A.PREP_STATUS = 4
AND B.ACCOUNT_NO NOT IN (select account_no from GVT_LAYOUT_FATURAS_CORP
                         where flag =5
                         and status = 'Ativo')
GROUP BY PAYMENT_DUE_DATE
order by 2