create table GVT_REL_ENCARGOS(
  ACCOUNT_NO                     NUMBER(10),
  BILL_REF_NO                    NUMBER(10),
  CONTA_COBRANCA                 NUMBER(12), 
  DESCRICAO_SERVICO              VARCHAR2(20),
  FATURA                         NUMBER(10),
  VENCIMENTO_FATURA_ATUAL        DATE,
  VALOR_FATURA_ATUAL             NUMBER(12),
  VALOR_ENCARGOS_FATURA_ATUAL    NUMBER(12),
  VENCIMENTO_FATURA_PAGA_ATRASO  NUMBER(12),
  DATA_PAGAMENTO_FATURA_ATRASADA DATE,
  VL_FATURA_EM_ATRASO            NUMBER(12),
  VL_FATURA_ATRASO_SEM_ENCARGOS  NUMBER(12))