SELECT A.ROW_ID,D.X_TEXTO_LIVRE 
FROM S_QUOTE_SOLN A, 
     S_QUOTE_ITEM B, 
     S_QTEITEM_PARAM C, 
     S_PARAM D
WHERE A.ROW_ID = B.QUOTE_SOLN_ID
 AND B.ROW_ID = C.QUOTE_ITEM_ID (+)
 AND C.PARAM_ID = D.ROW_ID (+)
 AND A.ASSET_NUM = 'SPO-3012I7QZ7-033'
 AND A.STATUS_CD = 'Ativo'
 AND A.COPIED_FLG = 'N'
 AND D.PARAM_NAME_ID IN ('1-BI76', '1-BIBZ', '1-BXLH', '1-BZ8T', '1-CTT6', '1-CTTG', '1-E4KN', '1-N69H', '1-1KTAO', '1-15GCHB', '1-275SQL', '1-8MKK1B')