DECLARE 
  P_CONTA_COBRANCA VARCHAR2(200);
  V_MENSAGEM VARCHAR2(200);
  V_BLOQUEAR NUMBER;

BEGIN 
  P_CONTA_COBRANCA := '899995637524';
  V_MENSAGEM := NULL;
  V_BLOQUEAR := NULL;

  ARBORGVT_BILLING.PROC_VALIDA_STATUS_CONTA ( P_CONTA_COBRANCA, V_MENSAGEM, V_BLOQUEAR );
  
  dbms_output.put_line(V_MENSAGEM);
  dbms_output.put_line(V_BLOQUEAR);

  COMMIT; 
END; 