 SELECT PL.BILL_REF_NO FATURA,
        NVL((TOTAL_DUE / 100),0) VALOR_PAGO,
        CASE WHEN TIPO  = '0001' THEN 'PAGAMENTO BANCO'   
             WHEN TIPO  = '0520' THEN 'PAGAMENTO ELETRONICO' 
        END TIPO_PAGAMENTO, 
        TO_CHAR(TRUNC(DT_PGTO),'DD/MM/YYYY') DATA_PAGAMENTO, 
        TO_CHAR(DT_PGTO,'HH24:MI:SS') HORA_PAGAMENTO, 
        TO_CHAR(TRUNC(PAYMENT_DUE_DATE),'DD/MM/YYYY') DATA_VENCIMENTO 
 FROM   GVT_PAGAMENTOS_LOTERICA PL, BILL_INVOICE BI 
 WHERE  EXTERNAL_ID = '999983860125'
 AND PL.BILL_REF_NO = BI.BILL_REF_NO 
 ORDER BY DT_PGTO, FATURA;