SELECT    B.BMF_TRANS_TYPE AS TIPO, 
                    DECODE(B.BMF_TRANS_TYPE, 1, TSV.DISPLAY_VALUE, DECODE (B.BMF_TRANS_TYPE,-264,D.DESCRIPTION_TEXT ||' - ' || DECODE(GPC.COD_BANCO,     999, 'VISA', 'REDECARD'), DECODE (B.BMF_TRANS_TYPE, -263,D.DESCRIPTION_TEXT ||' - ' || CL.CARD_CARRIER, D.DESCRIPTION_TEXT ) ) ) AS DESCRICAO,                     
                   SUM(GL_AMOUNT/100) AS VALOR, 
                   COUNT(1) AS QUANTIDADE
         FROM      BMF B, 
                   DESCRIPTIONS D,
                   BMF_TRANS_DESCR BTD,
                   TRANS_SOURCE_VALUES TSV,
                   GVT_PAGAMENTOS_CARTAO GPC,
                   PAYMENT_TRANS CT,
                   PAYMENT_PROFILE CL   
         WHERE     B.BMF_TRANS_TYPE = BTD.BMF_TRANS_TYPE
         AND       BTD.DESCRIPTION_CODE = D.DESCRIPTION_CODE
         AND       TSV.TRANS_SOURCE = B.TRANS_SOURCE
         AND       GPC.BILL_REF_NO (+) = B.ORIG_BILL_REF_NO
         AND       CT.BILL_REF_NO (+) = B.ORIG_BILL_REF_NO
         AND       CT.BILL_REF_RESETS (+) = B.ORIG_BILL_REF_RESETS
         AND       CT.PROFILE_ID (+) = B.PAYMENT_PROFILE_ID
         AND       CL.ACCOUNT_NO (+) =B.ACCOUNT_NO
         AND       TSV.LANGUAGE_CODE = 2
         AND       D.LANGUAGE_CODE = 2
         and       B.bmf_trans_type = -123
         AND       B.TRANS_DATE >= TO_DATE('01/03/2012','DD/MM/RRRR') 
         AND       B.TRANS_DATE <TO_DATE('01/05/2012','DD/MM/RRRR')
         GROUP BY  B.BMF_TRANS_TYPE, 
                    DECODE(B.BMF_TRANS_TYPE, 1, TSV.DISPLAY_VALUE, DECODE (B.BMF_TRANS_TYPE,-264,D.DESCRIPTION_TEXT ||' - ' || DECODE(GPC.COD_BANCO,     999, 'VISA', 'REDECARD'), DECODE (B.BMF_TRANS_TYPE, -263,D.DESCRIPTION_TEXT ||' - ' || CL.CARD_CARRIER, D.DESCRIPTION_TEXT ) ) );
