CREATE UNIQUE INDEX GVT_FEBRABAN_ARBOR_KEY0002 ON GVT_FEBRABAN_PONTA_B_ARBOR_B
(EMF_EXT_ID, ROW_ID)
LOGGING
TABLESPACE GVT_DEFAULT_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;