
Insert into G0023421SQL.GVT_VAL_PLANO
   (PLANO, COMPONENT_ID, COMPONENTE, ELEMENTOSCOMPONENTE, ELEMENTO, TIPOELEMENTO, ARQUIVO, NOME_PLANO)
 Values
   ('GVT - Na Medida Casa', '25011', 'Plano Basico - 5 minutos', NULL, NULL, 'RC - Conta', NULL, 'LAVOISIER');


Insert into G0023421SQL.GVT_VAL_PLANO
   (PLANO, COMPONENT_ID, COMPONENTE, ELEMENTOSCOMPONENTE, ELEMENTO, TIPOELEMENTO, ARQUIVO, NOME_PLANO)
 Values
   ('GVT Ilimitado Local Favoritos', '9999', 'GVT Ilimitado Local Favoritos', '4', NULL,'RC - Conta', NULL, 'TOUCHE');