SELECT POINT_CLASS 
FROM USAGE_POINTS
WHERE POINT = ?
AND   INACTIVE_DT IS NULL
UNION
SELECT MIN(point_class)
FROM USAGE_POINTS
WHERE POINT_STATE_ABBR = RPAD(?, 6)
AND   INACTIVE_DT IS NULL
AND LENGTH(point_class)=5