SELECT *
FROM USAGE_POINTS
WHERE POINT = ?
AND   INACTIVE_DT IS NULL
UNION
SELECT MIN(point_class)
FROM USAGE_POINTS
WHERE POINT_STATE_ABBR = RPAD(?, 6)
AND   INACTIVE_DT IS NULL
AND LENGTH(point_class)=5

-- ONDE POINT = COLUNA 2 DO PASSO 6 POINT_STATE_ABBR = COLUNA 7 DO PASSO 4

SELECT B.ROW_ID,B.ASSET_NUM AS PILOTO
FROM GVTPRD.S_QUOTE_SOLN A, 
     GVTPRD.S_QUOTE_SOLN B 
     
select * from S_QUOTE_SOLN where ASSET_NUM = 'CTA-3016T7FMP-032'


SELECT B.ROW_ID,B.ASSET_NUM AS PILOTO
FROM S_QUOTE_SOLN A, 
     S_QUOTE_SOLN B 
WHERE A.ASSET_NUM = 'CAS-3012X1LW1'
 AND A.STATUS_CD = 'Ativo'
 --AND A.SERV_PROD_ID = '1+1M7L+4706'
 AND A.X_APONTAMENTO_ID = B.ROW_ID
 
 
SELECT A.ROW_ID,D.X_TEXTO_LIVRE 
FROM S_QUOTE_SOLN A, 
     S_QUOTE_ITEM B, 
     S_QTEITEM_PARAM C, 
     S_PARAM D
WHERE A.ROW_ID = B.QUOTE_SOLN_ID
 AND B.ROW_ID = C.QUOTE_ITEM_ID (+)
 AND C.PARAM_ID = D.ROW_ID (+)
 AND A.ASSET_NUM = 'CAS-3012X1LW1'
 AND A.STATUS_CD = 'Ativo'
 AND D.PARAM_NAME_ID IN ('1-BI76', '1-BIBZ', '1-BXLH', '1-BZ8T', '1-CTT6', '1-CTTG', '1-E4KN', '1-N69H', '1-1KTAO', '1-15GCHB', '1-275SQL', '1-8MKK1B')