

CREATE TABLE COBILLING.RETORNO_ENVIADOS
(
  DSNAME            VARCHAR2(60 BYTE)           NOT NULL,
  EOT               VARCHAR2(3 BYTE),
  QTDE_REGISTRO     NUMBER(10),
  VALOR_LIQUIDO     NUMBER(18,2),
  DT_ENVIO          DATE                        NOT NULL,
  OPERADORA         VARCHAR2(3 BYTE),
  N_PROCESSO        NUMBER(10),
  DT_PROTOCOLO      DATE,
  STATUS_PROT       NUMBER(1),
  COD_CRITICA_PROT  VARCHAR2(2 BYTE)
);