SELECT EIAM.ACCOUNT_NO,CMF_EXT_ID, EMF_EXT_ID, 
       SERVICE_START, EIAM.INACTIVE_DATE
FROM   GVT_FEBRABAN_PONTA_B_ARBOR GFB,
       CUSTOMER_ID_ACCT_MAP EIAM
WHERE  GFB.CMF_EXT_ID = EIAM.EXTERNAL_ID
AND    EIAM.EXTERNAL_ID_TYPE =1
AND    GFB.SERVICE_END IS NULL