select M.TIPO_ERRO,
       M.EXTERNAL_ID, 
       P.CUST_BANK_ACC_NUM,
       P.ACCOUNT_NO, 
       M.STATUS_CADASTRAMENTO STATUS, 
       M.PAY_METHOD PAY_METHOD_DACC, 
       P.PAY_METHOD PAY_METHOD_PAYMENT, 
       b.BANK_NAME,
       M.COD_AGENTE_ARRECADADOR COD_AGENTE_ARRECADADOR_DACC, 
       P.CLEARING_HOUSE_ID COD_AGENTE_ARRECADADOR_PAYMENT,
       M.COD_AGENCIA COD_AGENCIA_DACC,
       P.CUST_BANK_SORT_CODE COD_AGENCIA_PAYMENT,
       M.NUM_CC_CARTAO NUM_CC_CARTAO_DACC, 
       P.OWNR_LNAME NUM_CC_CARTAO_OWNR_LNAME,
       P.CUST_BANK_ACC_NUM
 from GVT_DACC_GERENCIA_MET_PGTO M,
      PAYMENT_PROFILE P,
      CUSTOMER_ID_ACCT_MAP A,
      bank_names b
 where M.EXTERNAL_ID = A.EXTERNAL_ID
  and A.ACCOUNT_NO = P.ACCOUNT_NO
  and M.PAY_METHOD <> P.PAY_METHOD
  and B.BANK_CODE = M.COD_AGENTE_ARRECADADOR
  and M.OLD_PAY_METHOD = 1
  and A.INACTIVE_DATE is null
  and A.EXTERNAL_ID_TYPE = 1
  --and P.BANK_ACCOUNT_TYPE is not null
  and trunc(M.DT_CADASTRO) > to_date ('01/01/2011', 'DD/MM/YYYY')
  --and P.account_no = 3515302
  and M.STATUS_CADASTRAMENTO = 3
  and P.PAY_METHOD <> 2
  and A.EXTERNAL_ID = 999996479586
  
  order by 1