DROP PUBLIC SYNONYM GRC_NAOFATURACONJUNTO;

CREATE PUBLIC SYNONYM GRC_NAOFATURACONJUNTO FOR GRCOWN.GRC_NAOFATURACONJUNTO;

GRANT SELECT ON GRCOWN.GRC_NAOFATURACONJUNTO TO R_COBILLING_RO;

GRANT SELECT, INSERT, UPDATE, DELETE ON GRCOWN.GRC_NAOFATURACONJUNTO to DBAREM;

