select EXTERNAL_ID,
       ACCOUNT_NO,
       BILL_REF_NO,
       BILL_PERIOD
       BILL_LNAME,
       FILE_NAME_MEN,
       FILE_NAME_CDR,
       DT_STATUS,
       PREP_DATE,
       VALOR_FATURA,
       CD_GERADO
  FROM ARBORGVT_BILLING.GVT_LOG_DET_FATURAMENTO_CD
WHERE DT_INCLUSAO > sysdate -10
   AND UPPER(BILL_PERIOD) in (SELECT BILL_PERIOD FROM ARBORGVT_BILLING.GVT_PROCESSAMENTO_CICLO WHERE PROCESSAMENTO = UPPER('P27'));
   
  -- Cadastro
  --select * from ARBORGVT_BILLING.GVT_DET_FATURAMENTO_CD

