select EXTERNAL_ID,
       ACCOUNT_NO,
       BILL_REF_NO,
       BILL_PERIOD
       BILL_LNAME,
       FILE_NAME_MEN,
       FILE_NAME_CDR,
       DT_STATUS,
       PREP_DATE,
       VALOR_FATURA,
       CD_GERADO
  FROM ARBORGVT_BILLING.GVT_LOG_DET_FATURAMENTO_CD
 WHERE DT_INCLUSAO > sysdate -10
   AND UPPER(BILL_PERIOD) in (SELECT BILL_PERIOD FROM ARBORGVT_BILLING.GVT_PROCESSAMENTO_CICLO WHERE PROCESSAMENTO = UPPER('P27'));


select CD.EXTERNAL_ID, CMF.ACCOUNT_NO, CMF.BILL_LNAME, CMF.NO_BILL 
  from CMF,
       GVT_LOTERICA_CONSULTA_CPFCNPJ cpf,
       ARBORGVT_BILLING.GVT_DET_FATURAMENTO_CD CD
 where CD.EXTERNAL_ID = CPF.EXTERNAL_ID
   and CPF.ACCOUNT_NO = CMF.ACCOUNT_NO
   and CMF.DATE_INACTIVE is null 
 
 select * from all_tables where OWNER = 'G0023421SQL'
 
 select count(1) from GVT_DET_FATURAMENTO_CD
 
 select * from GVT_campanhas_ESPECIAIS