DECLARE 
  P_PARCEIRO NUMBER;
  FILE_DIR_LOG VARCHAR2(32767);
  FILE_NAME_LOG VARCHAR2(32767);

BEGIN 
  P_PARCEIRO := 37;
  FILE_DIR_LOG := 'GVT_COBILLING_LOG';
  FILE_NAME_LOG := 'PROC_ENVIA_CONTESTADOS_G2EOTAG'||'_'||to_char(sysdate,'yyyymmddhh24miss')||'.log';
  --GRCOWN.PROC_ENVIA_CONTESTADOS_G2EOTAG ( P_PARCEIRO, FILE_DIR_LOG, FILE_NAME_LOG );
  PROC_ENVIA_CONTESTADOS_G2EOTAG('37','GVT_COBILLING_LOG','PROC_ENVIA_CONTESTADOS_G2EOTAG'||'_'||to_char(sysdate,'yyyymmddhh24miss')||'.log');
  COMMIT; 
END;

select * from grc_parceiros