

CREATE TABLE ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE
(
  ACCOUNT_NO            NUMBER(10),
  BILL_REF_NO           NUMBER(10),
  BILL_REF_RESETS       NUMBER(3),
  IMAGE_DONE            NUMBER(1),
  PREP_STATUS           NUMBER(6),
  FORMAT_STATUS         NUMBER(6),
  FILE_NAME             CHAR(40 BYTE),
  START_OFFSET          NUMBER(10),
  END_OFFSET            NUMBER(10),
  PAGE_COUNT            NUMBER(6),
  PREP_ERROR_CODE       NUMBER(6),
  FORMAT_ERROR_CODE     NUMBER(6),
  BACKOUT_STATUS        NUMBER(6),
  ORIG_BILL_REFNO       NUMBER(10),
  ORIG_BILL_REF_RESETS  NUMBER(3),
  LANGUAGE_CODE         NUMBER(6)
);


CREATE INDEX ARBORGVT_BILLING.GFFBI_XBI_IDX_BILL_REF ON ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE
(BILL_REF_NO, BILL_REF_RESETS)
LOGGING
TABLESPACE GVT_FAT_CONTAB_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP SYNONYM ARBOR.GVT_FBB_BILL_INVOICE;

CREATE SYNONYM ARBOR.GVT_FBB_BILL_INVOICE FOR ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE;


DROP SYNONYM ARBORGVT_BILLING_AA1.GVT_FBB_BILL_INVOICE;

CREATE SYNONYM ARBORGVT_BILLING_AA1.GVT_FBB_BILL_INVOICE FOR ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE;


DROP PUBLIC SYNONYM GVT_FBB_BILL_INVOICE;

CREATE PUBLIC SYNONYM GVT_FBB_BILL_INVOICE FOR ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE;


ALTER TABLE ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE ADD (
  CONSTRAINT GVT_FBB_BI_BACKOUT_STATUS_CH
 CHECK (backout_status IN (0,1001,1002)),
  CONSTRAINT GVT_FBB_BI_FORMAT_STATUS_CH
 CHECK (format_status IN (-1,0,1,2,3)),
  CONSTRAINT GVT_FBB_BI_PREP_STATUS_CH
 CHECK (prep_status IN (0,1,2,3,4,5,1003,1004)),
  CHECK ("ACCOUNT_NO" IS NOT NULL),
  CHECK ("BILL_REF_NO" IS NOT NULL),
  CHECK ("BILL_REF_RESETS" IS NOT NULL),
  CHECK ("IMAGE_DONE" IS NOT NULL),
  CHECK ("PREP_STATUS" IS NOT NULL),
  CHECK ("PAGE_COUNT" IS NOT NULL),
  CHECK ("BACKOUT_STATUS" IS NOT NULL));

GRANT SELECT ON ARBORGVT_BILLING.GVT_FBB_BILL_INVOICE TO ARBOR;
