SELECT B.BILL_REF_NO,
         B.FEDERAL_RATE, 
         C.SHORT_DISPLAY, 
         B.TAX_PKG_INST_ID, 
         B.TAX_RATE,
         B.BILL_INVOICE_ROW
     FROM ARBOR.BILL_INVOICE_DETAIL A,
          ARBOR.BILL_INVOICE_TAX B,
          ARBOR.TAX_PKG_INST_ID_VALUES C
    WHERE A.BILL_REF_NO = ?
      AND A.BILL_REF_NO = B.BILL_REF_NO
      AND A.BILL_REF_RESETS = B.BILL_REF_RESETS
      AND A.BILL_INVOICE_ROW = B.BILL_INVOICE_ROW
      AND B.TAX_PKG_INST_ID = C.TAX_PKG_INST_ID
      AND C.LANGUAGE_CODE = 2
      AND B.FEDERAL_TAX > 0
      AND UPPER(C.DISPLAY_VALUE) LIKE '%ICMS%'