DECLARE 
  P_PARCEIRO NUMBER;
  P_NOME_ARQ_LOG VARCHAR2(32767);

BEGIN 
  P_PARCEIRO := 33;
  P_NOME_ARQ_LOG := 'teste_aurelio.log';

  GRCOWN.PROC_ENVIA_PARCEIRO_GV2EOTAG ( P_PARCEIRO, P_NOME_ARQ_LOG );
  COMMIT; 
END; 