CREATE TABLE PROFORMA_FULL
(
  EXTERNAL_ID       VARCHAR2(144 BYTE)          NOT NULL,
  BILL_PERIOD       VARCHAR2(3 BYTE)            NOT NULL,
  ELEMENT_ID        NUMBER(10),
  BILL_REF_NO       NUMBER(10)                  NOT NULL,
  TYPE_CODE         NUMBER(6)                   NOT NULL,
  SUBTYPE_CODE      NUMBER(10)                  NOT NULL,
  DESCRIPTION_TEXT  VARCHAR2(240 BYTE)          NOT NULL,
  VALOR             NUMBER,
  VALOR_LIQ         NUMBER,
  DISCOUNT          NUMBER,
  FEDERAL_TAX       NUMBER,
  BILL_INVOICE_ROW  NUMBER(10)                  NOT NULL,
  SUBSCR_NO         NUMBER(10)                  NOT NULL,
  TAX               NUMBER(18)                  NOT NULL,
  TAX_PKG_INST_ID   NUMBER(10),
  TAX_RATE          NUMBER(10)                  NOT NULL,
  FROM_DATE         DATE                        NOT NULL,
  TO_DATE           DATE                        NOT NULL,
  RATE_TYPE         NUMBER(10)                  NOT NULL,
  APARECE_NOTA      VARCHAR2(1 BYTE),
  COD_FISCAL        NUMBER(4),
  TIPO_UTILIZACAO   CHAR(1 BYTE),
  SUBTYPE_OUTRAS    VARCHAR2(1 BYTE),
  COD_DESCONTO      NUMBER,
  PREP_DATE         DATE                        NOT NULL,
  UNITS             NUMBER(10),
  TRACKING_ID       NUMBER(10)
);