select * from PRE_MEDIATION_OWNER.GVT_PMED_CDR

select * from PRE_MEDIATION_OWNER.GVT_PMED_CDR_PARTIAL

select * from PRE_MEDIATION_OWNER.GVT_PMED_CDR_FILE_TRACK

select * from PRE_MEDIATION_OWNER.GVT_PMED_CDR_FILE