CREATE TABLE GVT_IMPRIME_AJUSTE_FATURA
(
  SEQUENCIAL       NUMBER(6)                    NOT NULL,
  ACCOUNT_NO       NUMBER(10),
  EXTERNAL_ID      VARCHAR2(144 BYTE),
  BILL_LNAME       VARCHAR2(168 BYTE),
  DATA_INSERT      DATE,
  TIPO_CONTATO     VARCHAR2(1 BYTE),
  CONTATO          VARCHAR2(168 BYTE),
  BOLETO_IMPRESSO  VARCHAR2(1 BYTE),
  BILL_REF_NO      NUMBER(10)                   NOT NULL,
  USUARIO          VARCHAR2(100 BYTE)           NOT NULL
);